ImmutableDenseMatrix([[s*ux**2*np.sin(s*np.sqrt(ux**2 + uy**2)/(l*r))/(l**2*r*np.sqrt(ux**2 + uy**2)),
                       s*ux*uy*np.sin(s*np.sqrt(ux**2 + uy**2)/(l*r))/(l**2*r*np.sqrt(ux**2 + uy**2)),
                       s*ux*np.cos(s*np.sqrt(ux**2 + uy**2)/(l*r))/(l**2*r),
                       -r*ux*(1 - np.cos(s*np.sqrt(ux**2 + uy**2)/(l*r)))/(ux**2 + uy**2) + s*ux*np.sin(s*np.sqrt(ux**2 + uy**2)/(l*r))/(l*np.sqrt(ux**2 + uy**2))],
                      [s*ux*uy*np.sin(s*np.sqrt(ux**2 + uy**2)/(l*r))/(l**2*r*np.sqrt(ux**2 + uy**2)),
                       -s*ux**2*np.sin(s*np.sqrt(ux**2 + uy**2)/(l*r))/(l**2*r*np.sqrt(ux**2 + uy**2)) + s*np.sqrt(ux**2 + uy**2)*np.sin(s*np.sqrt(ux**2 + uy**2)/(l*r))/(l**2*r),
                       s*uy*np.cos(s*np.sqrt(ux**2 + uy**2)/(l*r))/(l**2*r),
                       -r*uy*(1 - np.cos(s*np.sqrt(ux**2 + uy**2)/(l*r)))/(ux**2 + uy**2) + s*uy*np.sin(s*np.sqrt(ux**2 + uy**2)/(l*r))/(l*np.sqrt(ux**2 + uy**2))],
                      [-s*ux*np.cos(s*np.sqrt(ux**2 + uy**2)/(l*r))/(l**2*r),
                       -s*uy*np.cos(s*np.sqrt(ux**2 + uy**2)/(l*r))/(l**2*r),
                       s*np.sqrt(ux**2 + uy**2)*np.sin(s*np.sqrt(ux**2 + uy**2)/(l*r))/(l**2*r),
                       r*np.sin(s*np.sqrt(ux**2 + uy**2)/(l*r))/np.sqrt(ux**2 + uy**2) - s*np.cos(s*np.sqrt(ux**2 + uy**2)/(l*r))/l],
                      [0, 0, 0, 0]])